openapi: 3.0.0
info:
  title: Loan Application API
  version: 1.0.0

paths:
  /api/accounts:
    get:
      summary: Get all accounts
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    account_id:
                      type: integer
                    account_name:
                      type: string
                    account_type:
                      type: string
                    balance:
                      type: number
                    pan_number:
                      type: string
                    tan_number:
                      type: string
    post:
      summary: Add new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [account_id, account_name, account_type, balance]
              properties:
                account_id:
                  type: integer
                account_name:
                  type: string
                account_type:
                  type: string
                  enum: [saving, current]
                balance:
                  type: number
                pan_number:
                  type: string
                tan_number:
                  type: string
      responses:
        '201':
          description: Account added
        '400':
          description: Bad request
        '500':
          description: Server error

  /api/accounts/{account_id}/loans:
    get:
      summary: Get loan eligibility for account
      parameters:
        - in: path
          name: account_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Eligible loans list
          content:
            application/json:
              schema:
                type: object
                properties:
                  eligible_loans:
                    type: array
                    items:
                      type: string
        '404':
          description: Account not found
